services:
  backend:
    image: frogfinance/signalcraft:latest
    build:
      context: .
      dockerfile: Dockerfile
      
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./dbs:/app/dbs


